services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: minepanel-backend
    ports:
      - "8091:8091"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./servers:/app/servers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - minepanel
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: minepanel-frontend
    ports:
      - "3000:8090"
    env_file:
      - .env
    networks:
      - minepanel
    restart: unless-stopped
    depends_on:
      - backend

networks:
  minepanel:
    driver: bridge

volumes:
  servers_data:
    driver: local
