version: '3'
services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - '25565:25565'
    environment:
      EULA: 'TRUE'
      MOTD: ATM 10 Tulalandia
      SERVER_NAME: TulaCraft
      DIFFICULTY: hard
      MAX_PLAYERS: '10'
      OPS: ketbome
      TZ: America/Santiago
      TYPE: AUTO_CURSEFORGE
      ONLINE_MODE: 'false'
      PVP: 'true'
      ENABLE_COMMAND_BLOCK: 'true'
      ALLOW_FLIGHT: 'true'
      VIEW_DISTANCE: '6'
      SIMULATION_DISTANCE: '4'
      STOP_SERVER_ANNOUNCE_DELAY: 60
      ENABLE_ROLLING_LOGS: 'true'
      EXEC_DIRECTLY: 'true'
      PLAYER_IDLE_TIMEOUT: '60'
      ENTITY_BROADCAST_RANGE_PERCENTAGE: '100'
      MODE: survival
      HARDCORE: 'false'
      SPAWN_ANIMALS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_NPCS: 'true'
      GENERATE_STRUCTURES: 'true'
      ALLOW_NETHER: 'true'
      UID: '1000'
      GID: '1000'
      INIT_MEMORY: 6G
      MAX_MEMORY: 10G
      ENABLE_RCON: 'true'
      RCON_PORT: '25575'
      OP_PERMISSION_LEVEL: '4'
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_FORCE_SYNCHRONIZE: 'true'
      CF_PARALLEL_DOWNLOADS: '4'
    volumes:
      - ./mc-data:/data
      - ./modpacks:/modpacks:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
        reservations:
          cpus: '0.3'
          memory: 4G
  init-filebrowser:
    image: filebrowser/filebrowser
    entrypoint: sh -c
    command:
      - 'chown -R 1000: /database'
    restart: 'no'
    volumes:
      - ./filebrowser-db:/database
  filebrowser:
    image: filebrowser/filebrowser
    depends_on:
      init-filebrowser:
        condition: service_completed_successfully
    user: '1000:1000'
    environment:
      FB_DATABASE: /database/filebrowser.db
    volumes:
      - ./:/srv
      - ./filebrowser-db:/database
    ports:
      - '25580:80'
    restart: unless-stopped
volumes:
  mc-data: {}
  filebrowser-db: {}
