version: '3'
services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    ports:
      - '25566:25565'
    environment:
      EULA: 'TRUE'
      MOTD: TulaCraft
      DIFFICULTY: hard
      MAX_PLAYERS: '10'
      OPS: ketbome
      TZ: America/Santiago
      INIT_MEMORY: 4G
      MAX_MEMORY: 6G
      TYPE: VANILLA
      VERSION: 1.19.2
      ONLINE_MODE: 'false'
      PVP: 'true'
      ENABLE_COMMAND_BLOCK: 'true'
      ALLOW_FLIGHT: 'true'
      VIEW_DISTANCE: '6'
      SIMULATION_DISTANCE: '4'
      STOP_SERVER_ANNOUNCE_DELAY: 60
      ENABLE_ROLLING_LOGS: 'true'
      EXEC_DIRECTLY: 'true'
      PLAYER_IDLE_TIMEOUT: '60'
    volumes:
      - ./mc-data:/data
      - ./modpacks:/modpacks:ro
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '0.3'
          memory: 4G
  init-filebrowser:
    image: filebrowser/filebrowser
    entrypoint: sh -c
    command:
      - 'chown -R 1000: /database'
    restart: 'no'
    volumes:
      - ./filebrowser-db:/database
  filebrowser:
    image: filebrowser/filebrowser
    depends_on:
      init-filebrowser:
        condition: service_completed_successfully
    user: '1000:1000'
    environment:
      FB_DATABASE: /database/filebrowser.db
    volumes:
      - ./:/srv
      - ./filebrowser-db:/database
    ports:
      - '25581:80'
    restart: unless-stopped
volumes:
  mc-data: {}
  filebrowser-db: {}
